<!--Includes CSS files -->
<link rel="stylesheet" href="css/bootstrap.min.css" >
<link rel="stylesheet" href="css/reset.css" >
<link rel="stylesheet" href="css/overall.css" >
<link rel="stylesheet" href="css/simple-inputs.css" >
<link rel="stylesheet" href="fa/fa_css/font-awesome-pro.css" >
<link rel="stylesheet" href="css/header.css" >
<link rel="stylesheet" href="css/shop-slidein.css" >
<link rel="stylesheet" href="css/step_1.css" >
<link rel="stylesheet" href="css/step_2.css" >
<link rel="stylesheet" href="css/step_3.css" >